import type { NutrientValues } from '../types';

export type FoodUnitMode = 'per100g' | 'per100ml' | 'serving';
export type AmountUnit = 'g' | 'ml';

export type FoodEntry = {
  id: string;
  /** マッチ用（長い語を優先するため長い順に登録する） */
  keywords: string[];
  name: string;
  /** 日本食品標準成分表ベースの概算値（100g または 100ml あたり） */
  nutrients: NutrientValues;
  mode: FoodUnitMode;
  /** per100g/ml のときの標準分量、serving のときは1食分 */
  defaultGrams: number;
  source: string;
  weight: number;
};

export function amountUnitOf(food: FoodEntry): AmountUnit {
  return food.mode === 'per100ml' ? 'ml' : 'g';
}

export function isScalableFood(food: FoodEntry): boolean {
  return food.mode === 'per100g' || food.mode === 'per100ml';
}

const EMPTY: NutrientValues = {
  energy_kcal: 0,
  protein_g: 0,
  fat_g: 0,
  carb_g: 0,
  salt_g: 0,
  fiber_g: 0,
  vitamin_c_mg: 0,
  calcium_mg: 0,
  iron_mg: 0,
};

/** 文部科学省 日本食品標準成分表を参考にした可食部100gあたり（または1食分） */
export const FOOD_DATABASE: FoodEntry[] = [
  // —— 野菜・果物（100g換算）——
  {
    id: 'broccoli',
    keywords: ['ブロッコリー', 'broccoli'],
    name: 'ブロッコリー（生）',
    nutrients: {
      energy_kcal: 33,
      protein_g: 4.3,
      fat_g: 0.5,
      carb_g: 6.6,
      salt_g: 0.05,
      fiber_g: 5.1,
      vitamin_c_mg: 140,
      calcium_mg: 38,
      iron_mg: 1.0,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 ブロッコリー/生',
    weight: 5,
  },
  {
    id: 'broccoli_boiled',
    keywords: ['ゆでブロッコリー', '茹でブロッコリー', 'ブロッコリーゆで'],
    name: 'ブロッコリー（ゆで）',
    nutrients: {
      energy_kcal: 33,
      protein_g: 3.9,
      fat_g: 0.4,
      carb_g: 6.0,
      salt_g: 0.04,
      fiber_g: 4.3,
      vitamin_c_mg: 54,
      calcium_mg: 38,
      iron_mg: 0.9,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 ブロッコリー/ゆで',
    weight: 6,
  },
  {
    id: 'cabbage',
    keywords: ['キャベツ'],
    name: 'キャベツ（生）',
    nutrients: {
      energy_kcal: 23,
      protein_g: 1.3,
      fat_g: 0.2,
      carb_g: 5.2,
      salt_g: 0.01,
      fiber_g: 1.8,
      vitamin_c_mg: 41,
      calcium_mg: 43,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: '日本食品標準成分表 キャベツ/生',
    weight: 5,
  },
  {
    id: 'carrot',
    keywords: ['にんじん', '人参', 'ニンジン'],
    name: 'にんじん（生）',
    nutrients: {
      energy_kcal: 39,
      protein_g: 0.7,
      fat_g: 0.2,
      carb_g: 9.3,
      salt_g: 0.07,
      fiber_g: 2.8,
      vitamin_c_mg: 6,
      calcium_mg: 28,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: '日本食品標準成分表 にんじん/根/皮むき/生',
    weight: 5,
  },
  {
    id: 'tomato',
    keywords: ['トマト'],
    name: 'トマト（生）',
    nutrients: {
      energy_kcal: 19,
      protein_g: 0.7,
      fat_g: 0.1,
      carb_g: 4.7,
      salt_g: 0.01,
      fiber_g: 1.0,
      vitamin_c_mg: 15,
      calcium_mg: 7,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 150,
    source: '日本食品標準成分表 トマト/果実/赤熟/生',
    weight: 5,
  },
  {
    id: 'cucumber',
    keywords: ['きゅうり', 'キュウリ'],
    name: 'きゅうり（生）',
    nutrients: {
      energy_kcal: 14,
      protein_g: 1.0,
      fat_g: 0.1,
      carb_g: 3.0,
      salt_g: 0.01,
      fiber_g: 1.1,
      vitamin_c_mg: 14,
      calcium_mg: 26,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 きゅうり/果実/生',
    weight: 5,
  },
  {
    id: 'spinach',
    keywords: ['ほうれん草', 'ホウレンソウ', 'ほうれんそう'],
    name: 'ほうれん草（生）',
    nutrients: {
      energy_kcal: 20,
      protein_g: 2.2,
      fat_g: 0.4,
      carb_g: 3.1,
      salt_g: 0.03,
      fiber_g: 2.8,
      vitamin_c_mg: 35,
      calcium_mg: 49,
      iron_mg: 2.0,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: '日本食品標準成分表 ほうれんそう/葉/生',
    weight: 5,
  },
  {
    id: 'lettuce',
    keywords: ['レタス'],
    name: 'レタス（生）',
    nutrients: {
      energy_kcal: 12,
      protein_g: 0.6,
      fat_g: 0.1,
      carb_g: 2.3,
      salt_g: 0.01,
      fiber_g: 1.1,
      vitamin_c_mg: 5,
      calcium_mg: 19,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: '日本食品標準成分表 レタス/結球葉/生',
    weight: 5,
  },
  {
    id: 'onion',
    keywords: ['玉ねぎ', 'たまねぎ', 'タマネギ'],
    name: '玉ねぎ（生）',
    nutrients: {
      energy_kcal: 37,
      protein_g: 1.0,
      fat_g: 0.1,
      carb_g: 8.8,
      salt_g: 0.01,
      fiber_g: 1.6,
      vitamin_c_mg: 8,
      calcium_mg: 21,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 たまねぎ/りん茎/生',
    weight: 5,
  },
  {
    id: 'potato',
    keywords: ['じゃがいも', 'ジャガイモ', 'ポテト'],
    name: 'じゃがいも（生）',
    nutrients: {
      energy_kcal: 76,
      protein_g: 1.6,
      fat_g: 0.1,
      carb_g: 17.6,
      salt_g: 0.0,
      fiber_g: 1.3,
      vitamin_c_mg: 35,
      calcium_mg: 3,
      iron_mg: 0.4,
    },
    mode: 'per100g',
    defaultGrams: 120,
    source: '日本食品標準成分表 じゃがいも/塊茎/生',
    weight: 5,
  },
  {
    id: 'banana',
    keywords: ['バナナ'],
    name: 'バナナ',
    nutrients: {
      energy_kcal: 86,
      protein_g: 1.1,
      fat_g: 0.2,
      carb_g: 22.5,
      salt_g: 0.0,
      fiber_g: 1.1,
      vitamin_c_mg: 16,
      calcium_mg: 6,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 バナナ/生',
    weight: 5,
  },
  {
    id: 'apple',
    keywords: ['りんご', 'リンゴ'],
    name: 'りんご',
    nutrients: {
      energy_kcal: 54,
      protein_g: 0.2,
      fat_g: 0.1,
      carb_g: 14.6,
      salt_g: 0.0,
      fiber_g: 1.5,
      vitamin_c_mg: 4,
      calcium_mg: 3,
      iron_mg: 0.1,
    },
    mode: 'per100g',
    defaultGrams: 200,
    source: '日本食品標準成分表 りんご/生/皮なし',
    weight: 5,
  },
  {
    id: 'egg_raw',
    keywords: ['ゆで卵', '茹で卵', 'ゆでたまご', '茹でたまご'],
    name: '鶏卵（ゆで）',
    nutrients: {
      energy_kcal: 151,
      protein_g: 12.3,
      fat_g: 10.3,
      carb_g: 0.3,
      salt_g: 0.35,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 51,
      iron_mg: 1.8,
    },
    mode: 'per100g',
    defaultGrams: 60,
    source: '日本食品標準成分表 鶏卵/全卵/ゆで',
    weight: 6,
  },
  {
    id: 'chicken_breast',
    keywords: ['鶏むね', '鶏胸', 'むね肉', '鶏むね肉'],
    name: '鶏むね肉（皮なし）',
    nutrients: {
      energy_kcal: 108,
      protein_g: 22.3,
      fat_g: 1.5,
      carb_g: 0,
      salt_g: 0.1,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 4,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 にわとり/むね/皮なし/生',
    weight: 5,
  },
  {
    id: 'tofu',
    keywords: ['豆腐', '木綿豆腐', '絹豆腐'],
    name: '木綿豆腐',
    nutrients: {
      energy_kcal: 72,
      protein_g: 6.6,
      fat_g: 4.2,
      carb_g: 1.6,
      salt_g: 0.03,
      fiber_g: 0.4,
      vitamin_c_mg: 0,
      calcium_mg: 93,
      iron_mg: 0.9,
    },
    mode: 'per100g',
    defaultGrams: 150,
    source: '日本食品標準成分表 豆腐/木綿',
    weight: 5,
  },
  {
    id: 'natto',
    keywords: ['納豆'],
    name: '納豆',
    nutrients: {
      energy_kcal: 200,
      protein_g: 16.5,
      fat_g: 10.0,
      carb_g: 12.1,
      salt_g: 2.0,
      fiber_g: 6.7,
      vitamin_c_mg: 0,
      calcium_mg: 90,
      iron_mg: 3.3,
    },
    mode: 'per100g',
    defaultGrams: 50,
    source: '日本食品標準成分表 糸引き納豆',
    weight: 5,
  },
  {
    id: 'rice_cooked',
    keywords: ['白米', 'ごはん', 'ご飯', 'ライス'],
    name: 'ご飯（精白米）',
    nutrients: {
      energy_kcal: 168,
      protein_g: 2.5,
      fat_g: 0.3,
      carb_g: 37.1,
      salt_g: 0.0,
      fiber_g: 0.3,
      vitamin_c_mg: 0,
      calcium_mg: 3,
      iron_mg: 0.1,
    },
    mode: 'per100g',
    defaultGrams: 150,
    source: '日本食品標準成分表 こめ/精白米/飯',
    weight: 4,
  },
  {
    id: 'yogurt',
    keywords: ['ヨーグルト'],
    name: 'ヨーグルト（全脂無糖）',
    nutrients: {
      energy_kcal: 62,
      protein_g: 3.6,
      fat_g: 3.0,
      carb_g: 5.0,
      salt_g: 0.13,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 120,
      iron_mg: 0.1,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 ヨーグルト/全脂無糖',
    weight: 5,
  },
  {
    id: 'salad_chicken',
    keywords: ['サラダチキン'],
    name: 'サラダチキン',
    nutrients: {
      energy_kcal: 110,
      protein_g: 23,
      fat_g: 1.5,
      carb_g: 0.5,
      salt_g: 1.5,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 10,
      iron_mg: 0.4,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '市販サラダチキンの代表値（100gあたり）',
    weight: 5,
  },

  // —— 飲料（100ml換算。成分表の100g値を密度≈1として利用）——
  {
    id: 'milk_whole',
    keywords: ['普通牛乳', '成分無調整牛乳', '牛乳', 'ミルク'],
    name: '普通牛乳',
    nutrients: {
      energy_kcal: 67,
      protein_g: 3.3,
      fat_g: 3.8,
      carb_g: 4.8,
      salt_g: 0.1,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 110,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 普通牛乳（100g≈100ml）',
    weight: 5,
  },
  {
    id: 'milk_lowfat',
    keywords: ['低脂肪牛乳', '低脂肪ミルク', '低脂肪乳'],
    name: '低脂肪牛乳',
    nutrients: {
      energy_kcal: 46,
      protein_g: 3.8,
      fat_g: 1.0,
      carb_g: 5.5,
      salt_g: 0.1,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 130,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 低脂肪牛乳',
    weight: 6,
  },
  {
    id: 'milk_skim',
    keywords: ['無脂肪牛乳', 'スキムミルク', '脱脂乳'],
    name: '無脂肪牛乳',
    nutrients: {
      energy_kcal: 33,
      protein_g: 3.4,
      fat_g: 0.1,
      carb_g: 4.7,
      salt_g: 0.1,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 120,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 無脂肪牛乳',
    weight: 6,
  },
  {
    id: 'soy_milk',
    keywords: ['無調整豆乳', '豆乳'],
    name: '豆乳（無調整）',
    nutrients: {
      energy_kcal: 46,
      protein_g: 3.6,
      fat_g: 2.0,
      carb_g: 3.1,
      salt_g: 0.0,
      fiber_g: 0.2,
      vitamin_c_mg: 0,
      calcium_mg: 15,
      iron_mg: 1.2,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 豆乳/無調整',
    weight: 5,
  },
  {
    id: 'soy_milk_prepared',
    keywords: ['調製豆乳'],
    name: '調製豆乳',
    nutrients: {
      energy_kcal: 64,
      protein_g: 3.2,
      fat_g: 3.6,
      carb_g: 4.8,
      salt_g: 0.1,
      fiber_g: 0.2,
      vitamin_c_mg: 0,
      calcium_mg: 64,
      iron_mg: 1.0,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 調製豆乳',
    weight: 6,
  },
  {
    id: 'orange_juice',
    keywords: ['オレンジジュース', 'オレンジ果汁', 'みかんジュース'],
    name: 'オレンジジュース',
    nutrients: {
      energy_kcal: 42,
      protein_g: 0.7,
      fat_g: 0.1,
      carb_g: 10.7,
      salt_g: 0.0,
      fiber_g: 0.3,
      vitamin_c_mg: 42,
      calcium_mg: 9,
      iron_mg: 0.2,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 オレンジ果汁',
    weight: 5,
  },
  {
    id: 'apple_juice',
    keywords: ['りんごジュース', 'アップルジュース', 'リンゴジュース'],
    name: 'りんごジュース',
    nutrients: {
      energy_kcal: 47,
      protein_g: 0.1,
      fat_g: 0.1,
      carb_g: 11.8,
      salt_g: 0.0,
      fiber_g: 0.2,
      vitamin_c_mg: 0,
      calcium_mg: 5,
      iron_mg: 0.1,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 りんご果汁',
    weight: 5,
  },
  {
    id: 'vegetable_juice',
    keywords: ['野菜ジュース', '野菜汁'],
    name: '野菜ジュース',
    nutrients: {
      energy_kcal: 20,
      protein_g: 0.7,
      fat_g: 0.1,
      carb_g: 4.6,
      salt_g: 0.3,
      fiber_g: 0.8,
      vitamin_c_mg: 20,
      calcium_mg: 15,
      iron_mg: 0.3,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '市販野菜ジュースの代表値（100mlあたり）',
    weight: 5,
  },
  {
    id: 'coffee_black',
    keywords: ['ブラックコーヒー', 'コーヒー'],
    name: 'コーヒー（浸出液）',
    nutrients: {
      energy_kcal: 4,
      protein_g: 0.2,
      fat_g: 0,
      carb_g: 0.7,
      salt_g: 0.0,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 2,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 150,
    source: '日本食品標準成分表 コーヒー/浸出液',
    weight: 4,
  },
  {
    id: 'green_tea',
    keywords: ['緑茶', '日本茶', 'お茶'],
    name: '緑茶（浸出液）',
    nutrients: {
      energy_kcal: 0,
      protein_g: 0,
      fat_g: 0,
      carb_g: 0,
      salt_g: 0.0,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 1,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 せん茶/浸出液',
    weight: 4,
  },
  {
    id: 'cola',
    keywords: ['コーラ', 'cola'],
    name: 'コーラ',
    nutrients: {
      energy_kcal: 46,
      protein_g: 0,
      fat_g: 0,
      carb_g: 11.4,
      salt_g: 0.02,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 2,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 350,
    source: '市販炭酸飲料の代表値（100mlあたり）',
    weight: 5,
  },
  {
    id: 'sports_drink',
    keywords: ['スポーツドリンク', 'ポカリスエット', 'アクエリアス', 'イオン飲料'],
    name: 'スポーツドリンク',
    nutrients: {
      energy_kcal: 25,
      protein_g: 0,
      fat_g: 0,
      carb_g: 6.2,
      salt_g: 0.12,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 2,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 500,
    source: '市販スポーツドリンクの代表値（100mlあたり）',
    weight: 5,
  },
  {
    id: 'beer',
    keywords: ['ビール'],
    name: 'ビール',
    nutrients: {
      energy_kcal: 40,
      protein_g: 0.3,
      fat_g: 0,
      carb_g: 3.1,
      salt_g: 0.0,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 2,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 350,
    source: '日本食品標準成分表 ビール/淡色',
    weight: 5,
  },

  // —— 料理（1食分の概算）——
  {
    id: 'oyakodon',
    keywords: ['親子丼', 'おやこどん'],
    name: '親子丼',
    nutrients: {
      energy_kcal: 720,
      protein_g: 32,
      fat_g: 22,
      carb_g: 95,
      salt_g: 3.8,
      fiber_g: 2.5,
      iron_mg: 2.1,
      vitamin_c_mg: 4,
      calcium_mg: 40,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 3,
  },
  {
    id: 'gyudon',
    keywords: ['牛丼', 'ぎゅうどん'],
    name: '牛丼',
    nutrients: {
      energy_kcal: 680,
      protein_g: 28,
      fat_g: 24,
      carb_g: 90,
      salt_g: 3.5,
      fiber_g: 2,
      iron_mg: 3.2,
      calcium_mg: 30,
      vitamin_c_mg: 2,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 3,
  },
  {
    id: 'ramen',
    keywords: ['ラーメン', 'らーめん', '拉麺'],
    name: 'ラーメン',
    nutrients: {
      energy_kcal: 650,
      protein_g: 24,
      fat_g: 28,
      carb_g: 78,
      salt_g: 6.5,
      fiber_g: 3,
      vitamin_c_mg: 2,
      calcium_mg: 50,
      iron_mg: 1.5,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 3,
  },
  {
    id: 'udon',
    keywords: ['うどん'],
    name: 'うどん',
    nutrients: {
      energy_kcal: 420,
      protein_g: 14,
      fat_g: 6,
      carb_g: 78,
      salt_g: 4.2,
      fiber_g: 2.5,
      calcium_mg: 35,
      iron_mg: 1.2,
      vitamin_c_mg: 1,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 2,
  },
  {
    id: 'soba',
    keywords: ['そば', '蕎麦'],
    name: 'そば',
    nutrients: {
      energy_kcal: 400,
      protein_g: 16,
      fat_g: 5,
      carb_g: 72,
      salt_g: 3.8,
      fiber_g: 4,
      iron_mg: 2.4,
      calcium_mg: 40,
      vitamin_c_mg: 1,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 2,
  },
  {
    id: 'curry',
    keywords: ['カレー', 'かれー'],
    name: 'カレーライス',
    nutrients: {
      energy_kcal: 750,
      protein_g: 22,
      fat_g: 26,
      carb_g: 108,
      salt_g: 3.6,
      fiber_g: 5,
      vitamin_c_mg: 12,
      iron_mg: 2.5,
      calcium_mg: 55,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 3,
  },
  {
    id: 'salad',
    keywords: ['サラダ'],
    name: 'サラダ',
    nutrients: {
      energy_kcal: 120,
      protein_g: 3,
      fat_g: 6,
      carb_g: 12,
      salt_g: 0.8,
      fiber_g: 4,
      vitamin_c_mg: 40,
      calcium_mg: 40,
      iron_mg: 1,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: 'ドレッシング込みの1食概算',
    weight: 2,
  },
  {
    id: 'bread',
    keywords: ['トースト', '食パン', 'パン'],
    name: '食パン（6枚切1枚）',
    nutrients: {
      energy_kcal: 158,
      protein_g: 5.6,
      fat_g: 2.6,
      carb_g: 28.0,
      salt_g: 0.8,
      fiber_g: 1.4,
      calcium_mg: 17,
      iron_mg: 0.4,
      vitamin_c_mg: 0,
    },
    mode: 'serving',
    defaultGrams: 60,
    source: '日本食品標準成分表 食パン 約60g',
    weight: 2,
  },
  {
    id: 'fish_dish',
    keywords: ['焼き魚', 'さば', '鮭', 'サーモン'],
    name: '魚料理',
    nutrients: {
      energy_kcal: 250,
      protein_g: 28,
      fat_g: 14,
      carb_g: 1,
      salt_g: 1.5,
      fiber_g: 0,
      iron_mg: 1.2,
      calcium_mg: 40,
      vitamin_c_mg: 1,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '焼き魚1食の概算',
    weight: 2,
  },
  {
    id: 'miso_soup',
    keywords: ['味噌汁', 'みそ汁'],
    name: '味噌汁',
    nutrients: {
      energy_kcal: 35,
      protein_g: 2.5,
      fat_g: 1.2,
      carb_g: 3.5,
      salt_g: 1.2,
      fiber_g: 0.8,
      calcium_mg: 30,
      iron_mg: 0.4,
      vitamin_c_mg: 1,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '味噌汁1杯の概算',
    weight: 2,
  },
  {
    id: 'bento',
    keywords: ['弁当', '定食'],
    name: '弁当・定食',
    nutrients: {
      energy_kcal: 700,
      protein_g: 28,
      fat_g: 22,
      carb_g: 95,
      salt_g: 3.5,
      fiber_g: 6,
      vitamin_c_mg: 20,
      calcium_mg: 80,
      iron_mg: 2.5,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '弁当・定食1食の概算',
    weight: 2,
  },
  {
    id: 'hamburger',
    keywords: ['ハンバーガー', 'バーガー'],
    name: 'ハンバーガー',
    nutrients: {
      energy_kcal: 550,
      protein_g: 25,
      fat_g: 28,
      carb_g: 48,
      salt_g: 2.4,
      fiber_g: 2,
      calcium_mg: 100,
      iron_mg: 2.5,
      vitamin_c_mg: 4,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: 'ハンバーガー1個の概算',
    weight: 2,
  },
  {
    id: 'steak',
    keywords: ['ステーキ', '焼肉'],
    name: '肉料理',
    nutrients: {
      energy_kcal: 450,
      protein_g: 35,
      fat_g: 30,
      carb_g: 5,
      salt_g: 2,
      fiber_g: 0,
      iron_mg: 3.5,
      calcium_mg: 20,
      vitamin_c_mg: 0,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '肉料理1食の概算',
    weight: 2,
  },
  {
    id: 'egg_dish',
    keywords: ['卵焼き', 'たまご焼き', 'スクランブルエッグ', '目玉焼き'],
    name: '卵料理',
    nutrients: {
      energy_kcal: 150,
      protein_g: 12,
      fat_g: 10,
      carb_g: 1,
      salt_g: 0.4,
      fiber_g: 0,
      iron_mg: 1.8,
      calcium_mg: 50,
      vitamin_c_mg: 0,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '卵料理1食の概算',
    weight: 2,
  },
];

export function emptyNutrients(): NutrientValues {
  return { ...EMPTY };
}
