import type { NutrientValues } from '../types';

export type FoodUnitMode = 'per100g' | 'per100ml' | 'serving';
export type AmountUnit = 'g' | 'ml';

export type FoodEntry = {
  id: string;
  /** マッチ用（長い語を優先するため長い順に登録する） */
  keywords: string[];
  name: string;
  /** 日本食品標準成分表ベースの概算値（100g または 100ml あたり） */
  nutrients: NutrientValues;
  mode: FoodUnitMode;
  /** per100g/ml のときの標準分量、serving のときは1食分 */
  defaultGrams: number;
  source: string;
  weight: number;
};

export function amountUnitOf(food: FoodEntry): AmountUnit {
  return food.mode === 'per100ml' ? 'ml' : 'g';
}

export function isScalableFood(food: FoodEntry): boolean {
  return food.mode === 'per100g' || food.mode === 'per100ml';
}

const EMPTY: NutrientValues = {
  energy_kcal: 0,
  protein_g: 0,
  fat_g: 0,
  carb_g: 0,
  salt_g: 0,
  fiber_g: 0,
  vitamin_c_mg: 0,
  calcium_mg: 0,
  iron_mg: 0,
};

/** 文部科学省 日本食品標準成分表を参考にした可食部100gあたり（または1食分） */
export const FOOD_DATABASE: FoodEntry[] = [
  // —— 野菜・果物（100g換算）——
  {
    id: 'broccoli',
    keywords: ['ブロッコリー', 'broccoli'],
    name: 'ブロッコリー（生）',
    nutrients: {
      energy_kcal: 33,
      protein_g: 4.3,
      fat_g: 0.5,
      carb_g: 6.6,
      salt_g: 0.05,
      fiber_g: 5.1,
      vitamin_c_mg: 140,
      calcium_mg: 38,
      iron_mg: 1.0,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 ブロッコリー/生',
    weight: 5,
  },
  {
    id: 'broccoli_boiled',
    keywords: ['ゆでブロッコリー', '茹でブロッコリー', 'ブロッコリーゆで'],
    name: 'ブロッコリー（ゆで）',
    nutrients: {
      energy_kcal: 33,
      protein_g: 3.9,
      fat_g: 0.4,
      carb_g: 6.0,
      salt_g: 0.04,
      fiber_g: 4.3,
      vitamin_c_mg: 54,
      calcium_mg: 38,
      iron_mg: 0.9,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 ブロッコリー/ゆで',
    weight: 6,
  },
  {
    id: 'cabbage',
    keywords: ['キャベツ'],
    name: 'キャベツ（生）',
    nutrients: {
      energy_kcal: 23,
      protein_g: 1.3,
      fat_g: 0.2,
      carb_g: 5.2,
      salt_g: 0.01,
      fiber_g: 1.8,
      vitamin_c_mg: 41,
      calcium_mg: 43,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: '日本食品標準成分表 キャベツ/生',
    weight: 5,
  },
  {
    id: 'carrot',
    keywords: ['にんじん', '人参', 'ニンジン'],
    name: 'にんじん（生）',
    nutrients: {
      energy_kcal: 39,
      protein_g: 0.7,
      fat_g: 0.2,
      carb_g: 9.3,
      salt_g: 0.07,
      fiber_g: 2.8,
      vitamin_c_mg: 6,
      calcium_mg: 28,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: '日本食品標準成分表 にんじん/根/皮むき/生',
    weight: 5,
  },
  {
    id: 'tomato',
    keywords: ['トマト'],
    name: 'トマト（生）',
    nutrients: {
      energy_kcal: 19,
      protein_g: 0.7,
      fat_g: 0.1,
      carb_g: 4.7,
      salt_g: 0.01,
      fiber_g: 1.0,
      vitamin_c_mg: 15,
      calcium_mg: 7,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 150,
    source: '日本食品標準成分表 トマト/果実/赤熟/生',
    weight: 5,
  },
  {
    id: 'cucumber',
    keywords: ['きゅうり', 'キュウリ'],
    name: 'きゅうり（生）',
    nutrients: {
      energy_kcal: 14,
      protein_g: 1.0,
      fat_g: 0.1,
      carb_g: 3.0,
      salt_g: 0.01,
      fiber_g: 1.1,
      vitamin_c_mg: 14,
      calcium_mg: 26,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 きゅうり/果実/生',
    weight: 5,
  },
  {
    id: 'spinach',
    keywords: ['ほうれん草', 'ホウレンソウ', 'ほうれんそう'],
    name: 'ほうれん草（生）',
    nutrients: {
      energy_kcal: 20,
      protein_g: 2.2,
      fat_g: 0.4,
      carb_g: 3.1,
      salt_g: 0.03,
      fiber_g: 2.8,
      vitamin_c_mg: 35,
      calcium_mg: 49,
      iron_mg: 2.0,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: '日本食品標準成分表 ほうれんそう/葉/生',
    weight: 5,
  },
  {
    id: 'lettuce',
    keywords: ['レタス'],
    name: 'レタス（生）',
    nutrients: {
      energy_kcal: 12,
      protein_g: 0.6,
      fat_g: 0.1,
      carb_g: 2.3,
      salt_g: 0.01,
      fiber_g: 1.1,
      vitamin_c_mg: 5,
      calcium_mg: 19,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: '日本食品標準成分表 レタス/結球葉/生',
    weight: 5,
  },
  {
    id: 'onion',
    keywords: ['玉ねぎ', 'たまねぎ', 'タマネギ'],
    name: '玉ねぎ（生）',
    nutrients: {
      energy_kcal: 37,
      protein_g: 1.0,
      fat_g: 0.1,
      carb_g: 8.8,
      salt_g: 0.01,
      fiber_g: 1.6,
      vitamin_c_mg: 8,
      calcium_mg: 21,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 たまねぎ/りん茎/生',
    weight: 5,
  },
  {
    id: 'potato',
    keywords: ['じゃがいも', 'ジャガイモ', 'ポテト'],
    name: 'じゃがいも（生）',
    nutrients: {
      energy_kcal: 76,
      protein_g: 1.6,
      fat_g: 0.1,
      carb_g: 17.6,
      salt_g: 0.0,
      fiber_g: 1.3,
      vitamin_c_mg: 35,
      calcium_mg: 3,
      iron_mg: 0.4,
    },
    mode: 'per100g',
    defaultGrams: 120,
    source: '日本食品標準成分表 じゃがいも/塊茎/生',
    weight: 5,
  },
  {
    id: 'banana',
    keywords: ['バナナ'],
    name: 'バナナ',
    nutrients: {
      energy_kcal: 86,
      protein_g: 1.1,
      fat_g: 0.2,
      carb_g: 22.5,
      salt_g: 0.0,
      fiber_g: 1.1,
      vitamin_c_mg: 16,
      calcium_mg: 6,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 バナナ/生',
    weight: 5,
  },
  {
    id: 'apple',
    keywords: ['りんご', 'リンゴ'],
    name: 'りんご',
    nutrients: {
      energy_kcal: 54,
      protein_g: 0.2,
      fat_g: 0.1,
      carb_g: 14.6,
      salt_g: 0.0,
      fiber_g: 1.5,
      vitamin_c_mg: 4,
      calcium_mg: 3,
      iron_mg: 0.1,
    },
    mode: 'per100g',
    defaultGrams: 200,
    source: '日本食品標準成分表 りんご/生/皮なし',
    weight: 5,
  },
  {
    id: 'egg_raw',
    keywords: ['ゆで卵', '茹で卵', 'ゆでたまご', '茹でたまご'],
    name: '鶏卵（ゆで）',
    nutrients: {
      energy_kcal: 151,
      protein_g: 12.3,
      fat_g: 10.3,
      carb_g: 0.3,
      salt_g: 0.35,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 51,
      iron_mg: 1.8,
    },
    mode: 'per100g',
    defaultGrams: 60,
    source: '日本食品標準成分表 鶏卵/全卵/ゆで',
    weight: 6,
  },
  {
    id: 'chicken_breast',
    keywords: ['鶏むね', '鶏胸', 'むね肉', '鶏むね肉'],
    name: '鶏むね肉（皮なし）',
    nutrients: {
      energy_kcal: 108,
      protein_g: 22.3,
      fat_g: 1.5,
      carb_g: 0,
      salt_g: 0.1,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 4,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 にわとり/むね/皮なし/生',
    weight: 5,
  },
  {
    id: 'tofu',
    keywords: ['豆腐', '木綿豆腐', '絹豆腐'],
    name: '木綿豆腐',
    nutrients: {
      energy_kcal: 72,
      protein_g: 6.6,
      fat_g: 4.2,
      carb_g: 1.6,
      salt_g: 0.03,
      fiber_g: 0.4,
      vitamin_c_mg: 0,
      calcium_mg: 93,
      iron_mg: 0.9,
    },
    mode: 'per100g',
    defaultGrams: 150,
    source: '日本食品標準成分表 豆腐/木綿',
    weight: 5,
  },
  {
    id: 'natto',
    keywords: ['納豆'],
    name: '納豆',
    nutrients: {
      energy_kcal: 200,
      protein_g: 16.5,
      fat_g: 10.0,
      carb_g: 12.1,
      salt_g: 2.0,
      fiber_g: 6.7,
      vitamin_c_mg: 0,
      calcium_mg: 90,
      iron_mg: 3.3,
    },
    mode: 'per100g',
    defaultGrams: 50,
    source: '日本食品標準成分表 糸引き納豆',
    weight: 5,
  },
  {
    id: 'rice_cooked',
    keywords: ['白米', 'ごはん', 'ご飯', 'ライス'],
    name: 'ご飯（精白米）',
    nutrients: {
      energy_kcal: 168,
      protein_g: 2.5,
      fat_g: 0.3,
      carb_g: 37.1,
      salt_g: 0.0,
      fiber_g: 0.3,
      vitamin_c_mg: 0,
      calcium_mg: 3,
      iron_mg: 0.1,
    },
    mode: 'per100g',
    defaultGrams: 150,
    source: '日本食品標準成分表 こめ/精白米/飯',
    weight: 4,
  },
  {
    id: 'yogurt',
    keywords: ['ヨーグルト'],
    name: 'ヨーグルト（全脂無糖）',
    nutrients: {
      energy_kcal: 62,
      protein_g: 3.6,
      fat_g: 3.0,
      carb_g: 5.0,
      salt_g: 0.13,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 120,
      iron_mg: 0.1,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 ヨーグルト/全脂無糖',
    weight: 5,
  },
  {
    id: 'salad_chicken',
    keywords: ['サラダチキン'],
    name: 'サラダチキン',
    nutrients: {
      energy_kcal: 110,
      protein_g: 23,
      fat_g: 1.5,
      carb_g: 0.5,
      salt_g: 1.5,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 10,
      iron_mg: 0.4,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '市販サラダチキンの代表値（100gあたり）',
    weight: 5,
  },

  // —— ナッツ・種実類（100g換算。既定はひとつかみ程度）——
  {
    id: 'almond',
    keywords: ['アーモンド', 'アーモンドナッツ'],
    name: 'アーモンド（いり・無塩）',
    nutrients: {
      energy_kcal: 578,
      protein_g: 21.3,
      fat_g: 54.1,
      carb_g: 20.9,
      salt_g: 0.0,
      fiber_g: 10.4,
      vitamin_c_mg: 0,
      calcium_mg: 230,
      iron_mg: 3.6,
    },
    mode: 'per100g',
    defaultGrams: 25,
    source: '日本食品標準成分表 アーモンド/いり/無塩',
    weight: 6,
  },
  {
    id: 'walnut',
    keywords: ['くるみ', 'クルミ', 'ウォールナッツ'],
    name: 'くるみ（いり）',
    nutrients: {
      energy_kcal: 674,
      protein_g: 14.6,
      fat_g: 68.8,
      carb_g: 11.7,
      salt_g: 0.0,
      fiber_g: 7.5,
      vitamin_c_mg: 0,
      calcium_mg: 85,
      iron_mg: 2.6,
    },
    mode: 'per100g',
    defaultGrams: 25,
    source: '日本食品標準成分表 くるみ/いり',
    weight: 6,
  },
  {
    id: 'cashew',
    keywords: ['カシューナッツ', 'カシュー'],
    name: 'カシューナッツ（いり・無塩）',
    nutrients: {
      energy_kcal: 576,
      protein_g: 19.8,
      fat_g: 47.7,
      carb_g: 26.9,
      salt_g: 0.0,
      fiber_g: 6.6,
      vitamin_c_mg: 0,
      calcium_mg: 40,
      iron_mg: 5.3,
    },
    mode: 'per100g',
    defaultGrams: 25,
    source: '日本食品標準成分表 カシューナッツ/いり/無塩',
    weight: 6,
  },
  {
    id: 'pistachio',
    keywords: ['ピスタチオ'],
    name: 'ピスタチオ（いり・無塩）',
    nutrients: {
      energy_kcal: 581,
      protein_g: 20.8,
      fat_g: 48.1,
      carb_g: 24.0,
      salt_g: 0.0,
      fiber_g: 9.3,
      vitamin_c_mg: 0,
      calcium_mg: 110,
      iron_mg: 3.5,
    },
    mode: 'per100g',
    defaultGrams: 25,
    source: '日本食品標準成分表 ピスタチオ/いり/無塩',
    weight: 6,
  },
  {
    id: 'peanut',
    keywords: ['ピーナッツ', '落花生', 'ピーナツ'],
    name: 'ピーナッツ（いり・無塩）',
    nutrients: {
      energy_kcal: 585,
      protein_g: 26.5,
      fat_g: 49.4,
      carb_g: 18.8,
      salt_g: 0.0,
      fiber_g: 8.0,
      vitamin_c_mg: 0,
      calcium_mg: 55,
      iron_mg: 1.8,
    },
    mode: 'per100g',
    defaultGrams: 25,
    source: '日本食品標準成分表 ピーナッツ/いり/無塩',
    weight: 6,
  },
  {
    id: 'macadamia',
    keywords: ['マカダミア', 'マカデミアナッツ'],
    name: 'マカダミアナッツ（いり・無塩）',
    nutrients: {
      energy_kcal: 720,
      protein_g: 8.2,
      fat_g: 76.2,
      carb_g: 12.7,
      salt_g: 0.0,
      fiber_g: 6.2,
      vitamin_c_mg: 0,
      calcium_mg: 70,
      iron_mg: 1.8,
    },
    mode: 'per100g',
    defaultGrams: 20,
    source: '日本食品標準成分表 マカダミアナッツ/いり/無塩',
    weight: 6,
  },
  {
    id: 'hazelnut',
    keywords: ['ヘーゼルナッツ', 'ヘーゼル'],
    name: 'ヘーゼルナッツ（いり）',
    nutrients: {
      energy_kcal: 684,
      protein_g: 13.6,
      fat_g: 64.9,
      carb_g: 17.0,
      salt_g: 0.0,
      fiber_g: 9.4,
      vitamin_c_mg: 0,
      calcium_mg: 130,
      iron_mg: 3.5,
    },
    mode: 'per100g',
    defaultGrams: 25,
    source: '日本食品標準成分表 ヘーゼルナッツ/いり',
    weight: 6,
  },
  {
    id: 'mixed_nuts',
    keywords: ['ミックスナッツ', 'ナッツ'],
    name: 'ミックスナッツ',
    nutrients: {
      energy_kcal: 610,
      protein_g: 18.0,
      fat_g: 54.0,
      carb_g: 20.0,
      salt_g: 0.2,
      fiber_g: 8.0,
      vitamin_c_mg: 0,
      calcium_mg: 120,
      iron_mg: 3.0,
    },
    mode: 'per100g',
    defaultGrams: 30,
    source: '市販ミックスナッツの代表値（100gあたり）',
    weight: 4,
  },
  {
    id: 'sesame',
    keywords: ['ごま', 'ゴマ', 'いりごま'],
    name: 'いりごま',
    nutrients: {
      energy_kcal: 578,
      protein_g: 19.8,
      fat_g: 51.9,
      carb_g: 18.5,
      salt_g: 0.0,
      fiber_g: 12.6,
      vitamin_c_mg: 0,
      calcium_mg: 1200,
      iron_mg: 9.9,
    },
    mode: 'per100g',
    defaultGrams: 10,
    source: '日本食品標準成分表 ごま/いり',
    weight: 5,
  },
  {
    id: 'chia_seed',
    keywords: ['チアシード'],
    name: 'チアシード',
    nutrients: {
      energy_kcal: 486,
      protein_g: 16.5,
      fat_g: 30.7,
      carb_g: 42.1,
      salt_g: 0.0,
      fiber_g: 34.4,
      vitamin_c_mg: 0,
      calcium_mg: 630,
      iron_mg: 7.7,
    },
    mode: 'per100g',
    defaultGrams: 15,
    source: '市販チアシードの代表値（100gあたり）',
    weight: 5,
  },

  // —— 果物・野菜・きのこ（追加）——
  {
    id: 'mandarin',
    keywords: ['みかん', 'ミカン', '温州みかん'],
    name: 'みかん',
    nutrients: {
      energy_kcal: 45,
      protein_g: 0.7,
      fat_g: 0.1,
      carb_g: 11.4,
      salt_g: 0.0,
      fiber_g: 0.7,
      vitamin_c_mg: 32,
      calcium_mg: 17,
      iron_mg: 0.1,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 うんしゅうみかん/生',
    weight: 5,
  },
  {
    id: 'strawberry',
    keywords: ['いちご', 'イチゴ'],
    name: 'いちご',
    nutrients: {
      energy_kcal: 34,
      protein_g: 0.9,
      fat_g: 0.1,
      carb_g: 8.5,
      salt_g: 0.0,
      fiber_g: 1.4,
      vitamin_c_mg: 62,
      calcium_mg: 17,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 いちご/生',
    weight: 5,
  },
  {
    id: 'grape',
    keywords: ['ぶどう', 'ブドウ'],
    name: 'ぶどう',
    nutrients: {
      energy_kcal: 59,
      protein_g: 0.4,
      fat_g: 0.1,
      carb_g: 15.7,
      salt_g: 0.0,
      fiber_g: 0.5,
      vitamin_c_mg: 2,
      calcium_mg: 6,
      iron_mg: 0.1,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 ぶどう/生',
    weight: 5,
  },
  {
    id: 'kiwi',
    keywords: ['キウイ', 'キウイフルーツ'],
    name: 'キウイフルーツ',
    nutrients: {
      energy_kcal: 53,
      protein_g: 1.0,
      fat_g: 0.1,
      carb_g: 13.5,
      salt_g: 0.0,
      fiber_g: 2.6,
      vitamin_c_mg: 69,
      calcium_mg: 26,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 キウイフルーツ/生',
    weight: 5,
  },
  {
    id: 'orange',
    keywords: ['オレンジ', 'ネーブル'],
    name: 'オレンジ',
    nutrients: {
      energy_kcal: 39,
      protein_g: 0.9,
      fat_g: 0.1,
      carb_g: 9.8,
      salt_g: 0.0,
      fiber_g: 1.3,
      vitamin_c_mg: 40,
      calcium_mg: 20,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 150,
    source: '日本食品標準成分表 オレンジ/生',
    weight: 5,
  },
  {
    id: 'avocado',
    keywords: ['アボカド'],
    name: 'アボカド',
    nutrients: {
      energy_kcal: 187,
      protein_g: 2.5,
      fat_g: 18.7,
      carb_g: 6.2,
      salt_g: 0.0,
      fiber_g: 5.3,
      vitamin_c_mg: 15,
      calcium_mg: 9,
      iron_mg: 0.6,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 アボカド/生',
    weight: 5,
  },
  {
    id: 'pumpkin',
    keywords: ['かぼちゃ', 'カボチャ'],
    name: 'かぼちゃ（ゆで）',
    nutrients: {
      energy_kcal: 80,
      protein_g: 1.9,
      fat_g: 0.1,
      carb_g: 19.9,
      salt_g: 0.0,
      fiber_g: 3.2,
      vitamin_c_mg: 12,
      calcium_mg: 18,
      iron_mg: 0.5,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 西洋かぼちゃ/ゆで',
    weight: 5,
  },
  {
    id: 'eggplant',
    keywords: ['なす', 'ナス', '茄子'],
    name: 'なす（生）',
    nutrients: {
      energy_kcal: 22,
      protein_g: 1.1,
      fat_g: 0.1,
      carb_g: 5.1,
      salt_g: 0.0,
      fiber_g: 2.2,
      vitamin_c_mg: 4,
      calcium_mg: 18,
      iron_mg: 0.3,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 なす/生',
    weight: 5,
  },
  {
    id: 'bell_pepper',
    keywords: ['ピーマン'],
    name: 'ピーマン（生）',
    nutrients: {
      energy_kcal: 22,
      protein_g: 0.9,
      fat_g: 0.2,
      carb_g: 5.1,
      salt_g: 0.0,
      fiber_g: 2.3,
      vitamin_c_mg: 76,
      calcium_mg: 11,
      iron_mg: 0.4,
    },
    mode: 'per100g',
    defaultGrams: 50,
    source: '日本食品標準成分表 ピーマン/生',
    weight: 5,
  },
  {
    id: 'daikon',
    keywords: ['大根', 'だいこん'],
    name: '大根（生）',
    nutrients: {
      energy_kcal: 18,
      protein_g: 0.5,
      fat_g: 0.1,
      carb_g: 4.1,
      salt_g: 0.0,
      fiber_g: 1.4,
      vitamin_c_mg: 12,
      calcium_mg: 24,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 だいこん/根/皮むき/生',
    weight: 5,
  },
  {
    id: 'mushroom_mix',
    keywords: ['きのこ', 'しいたけ', 'えのき', 'しめじ', 'まいたけ', 'エリンギ'],
    name: 'きのこ類',
    nutrients: {
      energy_kcal: 25,
      protein_g: 3.0,
      fat_g: 0.4,
      carb_g: 5.0,
      salt_g: 0.0,
      fiber_g: 4.0,
      vitamin_c_mg: 2,
      calcium_mg: 5,
      iron_mg: 0.5,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: 'きのこ類の代表値（100gあたり）',
    weight: 4,
  },

  // —— 肉・魚・乳製品・炭水化物（追加）——
  {
    id: 'salmon',
    keywords: ['鮭', 'サケ', 'サーモン'],
    name: '鮭（しろさけ・生）',
    nutrients: {
      energy_kcal: 133,
      protein_g: 22.3,
      fat_g: 4.1,
      carb_g: 0.1,
      salt_g: 0.2,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 14,
      iron_mg: 0.5,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: '日本食品標準成分表 しろさけ/生',
    weight: 5,
  },
  {
    id: 'mackerel',
    keywords: ['さば', 'サバ', '鯖'],
    name: 'さば（生）',
    nutrients: {
      energy_kcal: 247,
      protein_g: 20.6,
      fat_g: 16.8,
      carb_g: 0.3,
      salt_g: 0.3,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 10,
      iron_mg: 1.2,
    },
    mode: 'per100g',
    defaultGrams: 80,
    source: '日本食品標準成分表 まさば/生',
    weight: 5,
  },
  {
    id: 'tuna_can',
    keywords: ['ツナ缶', 'ツナ', 'まぐろ缶'],
    name: 'ツナ缶（油漬・水切り）',
    nutrients: {
      energy_kcal: 207,
      protein_g: 17.7,
      fat_g: 14.5,
      carb_g: 0.1,
      salt_g: 0.9,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 5,
      iron_mg: 1.2,
    },
    mode: 'per100g',
    defaultGrams: 70,
    source: '日本食品標準成分表 まぐろ/缶/油漬',
    weight: 5,
  },
  {
    id: 'pork',
    keywords: ['豚肉', '豚ロース', '豚こま'],
    name: '豚肉（ロース・生）',
    nutrients: {
      energy_kcal: 263,
      protein_g: 19.3,
      fat_g: 19.2,
      carb_g: 0.2,
      salt_g: 0.1,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 4,
      iron_mg: 0.5,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 ぶた/ロース/生',
    weight: 5,
  },
  {
    id: 'beef',
    keywords: ['牛肉', '牛もも', '牛こま'],
    name: '牛肉（もも・生）',
    nutrients: {
      energy_kcal: 182,
      protein_g: 21.3,
      fat_g: 9.6,
      carb_g: 0.3,
      salt_g: 0.1,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 4,
      iron_mg: 2.4,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 うし/もも/生',
    weight: 5,
  },
  {
    id: 'cheese',
    keywords: ['チーズ', 'プロセスチーズ', 'チェダー'],
    name: 'プロセスチーズ',
    nutrients: {
      energy_kcal: 313,
      protein_g: 22.7,
      fat_g: 26.0,
      carb_g: 1.3,
      salt_g: 2.8,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 630,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 20,
    source: '日本食品標準成分表 プロセスチーズ',
    weight: 5,
  },
  {
    id: 'oatmeal',
    keywords: ['オートミール', 'オーツ'],
    name: 'オートミール（乾）',
    nutrients: {
      energy_kcal: 380,
      protein_g: 13.7,
      fat_g: 5.7,
      carb_g: 69.1,
      salt_g: 0.0,
      fiber_g: 9.4,
      vitamin_c_mg: 0,
      calcium_mg: 47,
      iron_mg: 3.9,
    },
    mode: 'per100g',
    defaultGrams: 40,
    source: '日本食品標準成分表 オートミール',
    weight: 5,
  },
  {
    id: 'pasta_boiled',
    keywords: ['パスタ', 'スパゲッティ', 'スパゲティ'],
    name: 'パスタ（ゆで）',
    nutrients: {
      energy_kcal: 149,
      protein_g: 5.2,
      fat_g: 0.9,
      carb_g: 28.8,
      salt_g: 0.0,
      fiber_g: 1.5,
      vitamin_c_mg: 0,
      calcium_mg: 12,
      iron_mg: 0.5,
    },
    mode: 'per100g',
    defaultGrams: 200,
    source: '日本食品標準成分表 マカロニ・スパゲッティ/ゆで',
    weight: 5,
  },
  {
    id: 'udon_boiled',
    keywords: ['ゆでうどん', '茹でうどん'],
    name: 'うどん（ゆで）',
    nutrients: {
      energy_kcal: 105,
      protein_g: 2.6,
      fat_g: 0.4,
      carb_g: 21.6,
      salt_g: 0.3,
      fiber_g: 0.8,
      vitamin_c_mg: 0,
      calcium_mg: 8,
      iron_mg: 0.2,
    },
    mode: 'per100g',
    defaultGrams: 200,
    source: '日本食品標準成分表 うどん/ゆで',
    weight: 5,
  },
  {
    id: 'sweet_potato',
    keywords: ['さつまいも', 'サツマイモ', '焼き芋'],
    name: 'さつまいも（蒸し）',
    nutrients: {
      energy_kcal: 131,
      protein_g: 1.2,
      fat_g: 0.2,
      carb_g: 31.5,
      salt_g: 0.0,
      fiber_g: 3.5,
      vitamin_c_mg: 20,
      calcium_mg: 36,
      iron_mg: 0.6,
    },
    mode: 'per100g',
    defaultGrams: 150,
    source: '日本食品標準成分表 さつまいも/蒸し',
    weight: 5,
  },
  {
    id: 'chocolate',
    keywords: ['チョコレート', 'チョコ'],
    name: 'ミルクチョコレート',
    nutrients: {
      energy_kcal: 557,
      protein_g: 7.0,
      fat_g: 34.0,
      carb_g: 55.0,
      salt_g: 0.2,
      fiber_g: 2.4,
      vitamin_c_mg: 0,
      calcium_mg: 220,
      iron_mg: 1.5,
    },
    mode: 'per100g',
    defaultGrams: 25,
    source: '日本食品標準成分表 ミルクチョコレート',
    weight: 5,
  },
  {
    id: 'edamame',
    keywords: ['枝豆', 'えだまめ'],
    name: '枝豆（ゆで）',
    nutrients: {
      energy_kcal: 135,
      protein_g: 11.5,
      fat_g: 6.1,
      carb_g: 8.9,
      salt_g: 0.0,
      fiber_g: 5.0,
      vitamin_c_mg: 15,
      calcium_mg: 66,
      iron_mg: 2.2,
    },
    mode: 'per100g',
    defaultGrams: 50,
    source: '日本食品標準成分表 えだまめ/ゆで',
    weight: 5,
  },
  {
    id: 'corn',
    keywords: ['とうもろこし', 'コーン'],
    name: 'とうもろこし（ゆで）',
    nutrients: {
      energy_kcal: 98,
      protein_g: 3.5,
      fat_g: 1.7,
      carb_g: 18.6,
      salt_g: 0.0,
      fiber_g: 3.0,
      vitamin_c_mg: 6,
      calcium_mg: 4,
      iron_mg: 0.5,
    },
    mode: 'per100g',
    defaultGrams: 100,
    source: '日本食品標準成分表 スイートコーン/ゆで',
    weight: 5,
  },
  {
    id: 'ham',
    keywords: ['ハム', 'ロースハム'],
    name: 'ロースハム',
    nutrients: {
      energy_kcal: 196,
      protein_g: 16.5,
      fat_g: 13.9,
      carb_g: 1.5,
      salt_g: 2.5,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 6,
      iron_mg: 0.7,
    },
    mode: 'per100g',
    defaultGrams: 40,
    source: '日本食品標準成分表 ロースハム',
    weight: 5,
  },
  {
    id: 'sausage',
    keywords: ['ソーセージ', 'ウインナー'],
    name: 'ウインナーソーセージ',
    nutrients: {
      energy_kcal: 321,
      protein_g: 13.2,
      fat_g: 28.5,
      carb_g: 3.0,
      salt_g: 2.0,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 10,
      iron_mg: 1.0,
    },
    mode: 'per100g',
    defaultGrams: 50,
    source: '日本食品標準成分表 ウインナーソーセージ',
    weight: 5,
  },

  // —— 飲料（100ml換算。成分表の100g値を密度≈1として利用）——
  {
    id: 'milk_whole',
    keywords: ['普通牛乳', '成分無調整牛乳', '牛乳', 'ミルク'],
    name: '普通牛乳',
    nutrients: {
      energy_kcal: 67,
      protein_g: 3.3,
      fat_g: 3.8,
      carb_g: 4.8,
      salt_g: 0.1,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 110,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 普通牛乳（100g≈100ml）',
    weight: 5,
  },
  {
    id: 'milk_lowfat',
    keywords: ['低脂肪牛乳', '低脂肪ミルク', '低脂肪乳'],
    name: '低脂肪牛乳',
    nutrients: {
      energy_kcal: 46,
      protein_g: 3.8,
      fat_g: 1.0,
      carb_g: 5.5,
      salt_g: 0.1,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 130,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 低脂肪牛乳',
    weight: 6,
  },
  {
    id: 'milk_skim',
    keywords: ['無脂肪牛乳', 'スキムミルク', '脱脂乳'],
    name: '無脂肪牛乳',
    nutrients: {
      energy_kcal: 33,
      protein_g: 3.4,
      fat_g: 0.1,
      carb_g: 4.7,
      salt_g: 0.1,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 120,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 無脂肪牛乳',
    weight: 6,
  },
  {
    id: 'soy_milk',
    keywords: ['無調整豆乳', '豆乳'],
    name: '豆乳（無調整）',
    nutrients: {
      energy_kcal: 46,
      protein_g: 3.6,
      fat_g: 2.0,
      carb_g: 3.1,
      salt_g: 0.0,
      fiber_g: 0.2,
      vitamin_c_mg: 0,
      calcium_mg: 15,
      iron_mg: 1.2,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 豆乳/無調整',
    weight: 5,
  },
  {
    id: 'soy_milk_prepared',
    keywords: ['調製豆乳'],
    name: '調製豆乳',
    nutrients: {
      energy_kcal: 64,
      protein_g: 3.2,
      fat_g: 3.6,
      carb_g: 4.8,
      salt_g: 0.1,
      fiber_g: 0.2,
      vitamin_c_mg: 0,
      calcium_mg: 64,
      iron_mg: 1.0,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 調製豆乳',
    weight: 6,
  },
  {
    id: 'orange_juice',
    keywords: ['オレンジジュース', 'オレンジ果汁', 'みかんジュース'],
    name: 'オレンジジュース',
    nutrients: {
      energy_kcal: 42,
      protein_g: 0.7,
      fat_g: 0.1,
      carb_g: 10.7,
      salt_g: 0.0,
      fiber_g: 0.3,
      vitamin_c_mg: 42,
      calcium_mg: 9,
      iron_mg: 0.2,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 オレンジ果汁',
    weight: 5,
  },
  {
    id: 'apple_juice',
    keywords: ['りんごジュース', 'アップルジュース', 'リンゴジュース'],
    name: 'りんごジュース',
    nutrients: {
      energy_kcal: 47,
      protein_g: 0.1,
      fat_g: 0.1,
      carb_g: 11.8,
      salt_g: 0.0,
      fiber_g: 0.2,
      vitamin_c_mg: 0,
      calcium_mg: 5,
      iron_mg: 0.1,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 りんご果汁',
    weight: 5,
  },
  {
    id: 'vegetable_juice',
    keywords: ['野菜ジュース', '野菜汁'],
    name: '野菜ジュース',
    nutrients: {
      energy_kcal: 20,
      protein_g: 0.7,
      fat_g: 0.1,
      carb_g: 4.6,
      salt_g: 0.3,
      fiber_g: 0.8,
      vitamin_c_mg: 20,
      calcium_mg: 15,
      iron_mg: 0.3,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '市販野菜ジュースの代表値（100mlあたり）',
    weight: 5,
  },
  {
    id: 'coffee_black',
    keywords: ['ブラックコーヒー', 'コーヒー'],
    name: 'コーヒー（浸出液）',
    nutrients: {
      energy_kcal: 4,
      protein_g: 0.2,
      fat_g: 0,
      carb_g: 0.7,
      salt_g: 0.0,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 2,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 150,
    source: '日本食品標準成分表 コーヒー/浸出液',
    weight: 4,
  },
  {
    id: 'green_tea',
    keywords: ['緑茶', '日本茶', 'お茶'],
    name: '緑茶（浸出液）',
    nutrients: {
      energy_kcal: 0,
      protein_g: 0,
      fat_g: 0,
      carb_g: 0,
      salt_g: 0.0,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 1,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 200,
    source: '日本食品標準成分表 せん茶/浸出液',
    weight: 4,
  },
  {
    id: 'cola',
    keywords: ['コーラ', 'cola'],
    name: 'コーラ',
    nutrients: {
      energy_kcal: 46,
      protein_g: 0,
      fat_g: 0,
      carb_g: 11.4,
      salt_g: 0.02,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 2,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 350,
    source: '市販炭酸飲料の代表値（100mlあたり）',
    weight: 5,
  },
  {
    id: 'sports_drink',
    keywords: ['スポーツドリンク', 'ポカリスエット', 'アクエリアス', 'イオン飲料'],
    name: 'スポーツドリンク',
    nutrients: {
      energy_kcal: 25,
      protein_g: 0,
      fat_g: 0,
      carb_g: 6.2,
      salt_g: 0.12,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 2,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 500,
    source: '市販スポーツドリンクの代表値（100mlあたり）',
    weight: 5,
  },
  {
    id: 'beer',
    keywords: ['ビール'],
    name: 'ビール',
    nutrients: {
      energy_kcal: 40,
      protein_g: 0.3,
      fat_g: 0,
      carb_g: 3.1,
      salt_g: 0.0,
      fiber_g: 0,
      vitamin_c_mg: 0,
      calcium_mg: 2,
      iron_mg: 0.0,
    },
    mode: 'per100ml',
    defaultGrams: 350,
    source: '日本食品標準成分表 ビール/淡色',
    weight: 5,
  },

  // —— 料理（1食分の概算）——
  {
    id: 'oyakodon',
    keywords: ['親子丼', 'おやこどん'],
    name: '親子丼',
    nutrients: {
      energy_kcal: 720,
      protein_g: 32,
      fat_g: 22,
      carb_g: 95,
      salt_g: 3.8,
      fiber_g: 2.5,
      iron_mg: 2.1,
      vitamin_c_mg: 4,
      calcium_mg: 40,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 3,
  },
  {
    id: 'gyudon',
    keywords: ['牛丼', 'ぎゅうどん'],
    name: '牛丼',
    nutrients: {
      energy_kcal: 680,
      protein_g: 28,
      fat_g: 24,
      carb_g: 90,
      salt_g: 3.5,
      fiber_g: 2,
      iron_mg: 3.2,
      calcium_mg: 30,
      vitamin_c_mg: 2,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 3,
  },
  {
    id: 'ramen',
    keywords: ['ラーメン', 'らーめん', '拉麺'],
    name: 'ラーメン',
    nutrients: {
      energy_kcal: 650,
      protein_g: 24,
      fat_g: 28,
      carb_g: 78,
      salt_g: 6.5,
      fiber_g: 3,
      vitamin_c_mg: 2,
      calcium_mg: 50,
      iron_mg: 1.5,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 3,
  },
  {
    id: 'udon',
    keywords: ['うどん'],
    name: 'うどん',
    nutrients: {
      energy_kcal: 420,
      protein_g: 14,
      fat_g: 6,
      carb_g: 78,
      salt_g: 4.2,
      fiber_g: 2.5,
      calcium_mg: 35,
      iron_mg: 1.2,
      vitamin_c_mg: 1,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 2,
  },
  {
    id: 'soba',
    keywords: ['そば', '蕎麦'],
    name: 'そば',
    nutrients: {
      energy_kcal: 400,
      protein_g: 16,
      fat_g: 5,
      carb_g: 72,
      salt_g: 3.8,
      fiber_g: 4,
      iron_mg: 2.4,
      calcium_mg: 40,
      vitamin_c_mg: 1,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 2,
  },
  {
    id: 'curry',
    keywords: ['カレー', 'かれー'],
    name: 'カレーライス',
    nutrients: {
      energy_kcal: 750,
      protein_g: 22,
      fat_g: 26,
      carb_g: 108,
      salt_g: 3.6,
      fiber_g: 5,
      vitamin_c_mg: 12,
      iron_mg: 2.5,
      calcium_mg: 55,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '外食・家庭料理の1食概算',
    weight: 3,
  },
  {
    id: 'salad',
    keywords: ['サラダ'],
    name: 'サラダ',
    nutrients: {
      energy_kcal: 120,
      protein_g: 3,
      fat_g: 6,
      carb_g: 12,
      salt_g: 0.8,
      fiber_g: 4,
      vitamin_c_mg: 40,
      calcium_mg: 40,
      iron_mg: 1,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: 'ドレッシング込みの1食概算',
    weight: 2,
  },
  {
    id: 'bread',
    keywords: ['トースト', '食パン', 'パン'],
    name: '食パン（6枚切1枚）',
    nutrients: {
      energy_kcal: 158,
      protein_g: 5.6,
      fat_g: 2.6,
      carb_g: 28.0,
      salt_g: 0.8,
      fiber_g: 1.4,
      calcium_mg: 17,
      iron_mg: 0.4,
      vitamin_c_mg: 0,
    },
    mode: 'serving',
    defaultGrams: 60,
    source: '日本食品標準成分表 食パン 約60g',
    weight: 2,
  },
  {
    id: 'fish_dish',
    keywords: ['焼き魚', '魚料理'],
    name: '魚料理',
    nutrients: {
      energy_kcal: 250,
      protein_g: 28,
      fat_g: 14,
      carb_g: 1,
      salt_g: 1.5,
      fiber_g: 0,
      iron_mg: 1.2,
      calcium_mg: 40,
      vitamin_c_mg: 1,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '焼き魚1食の概算',
    weight: 2,
  },
  {
    id: 'miso_soup',
    keywords: ['味噌汁', 'みそ汁'],
    name: '味噌汁',
    nutrients: {
      energy_kcal: 35,
      protein_g: 2.5,
      fat_g: 1.2,
      carb_g: 3.5,
      salt_g: 1.2,
      fiber_g: 0.8,
      calcium_mg: 30,
      iron_mg: 0.4,
      vitamin_c_mg: 1,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '味噌汁1杯の概算',
    weight: 2,
  },
  {
    id: 'bento',
    keywords: ['弁当', '定食'],
    name: '弁当・定食',
    nutrients: {
      energy_kcal: 700,
      protein_g: 28,
      fat_g: 22,
      carb_g: 95,
      salt_g: 3.5,
      fiber_g: 6,
      vitamin_c_mg: 20,
      calcium_mg: 80,
      iron_mg: 2.5,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '弁当・定食1食の概算',
    weight: 2,
  },
  {
    id: 'hamburger',
    keywords: ['ハンバーガー', 'バーガー'],
    name: 'ハンバーガー',
    nutrients: {
      energy_kcal: 550,
      protein_g: 25,
      fat_g: 28,
      carb_g: 48,
      salt_g: 2.4,
      fiber_g: 2,
      calcium_mg: 100,
      iron_mg: 2.5,
      vitamin_c_mg: 4,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: 'ハンバーガー1個の概算',
    weight: 2,
  },
  {
    id: 'steak',
    keywords: ['ステーキ', '焼肉'],
    name: '肉料理',
    nutrients: {
      energy_kcal: 450,
      protein_g: 35,
      fat_g: 30,
      carb_g: 5,
      salt_g: 2,
      fiber_g: 0,
      iron_mg: 3.5,
      calcium_mg: 20,
      vitamin_c_mg: 0,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '肉料理1食の概算',
    weight: 2,
  },
  {
    id: 'egg_dish',
    keywords: ['卵焼き', 'たまご焼き', 'スクランブルエッグ', '目玉焼き'],
    name: '卵料理',
    nutrients: {
      energy_kcal: 150,
      protein_g: 12,
      fat_g: 10,
      carb_g: 1,
      salt_g: 0.4,
      fiber_g: 0,
      iron_mg: 1.8,
      calcium_mg: 50,
      vitamin_c_mg: 0,
    },
    mode: 'serving',
    defaultGrams: 1,
    source: '卵料理1食の概算',
    weight: 2,
  },
];

export function emptyNutrients(): NutrientValues {
  return { ...EMPTY };
}
